server:
  port: 56002
spring:
  datasource:
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/learning?useUnicode=true&characterEncoding=utf8&serverTimeZone=CTT&stringtype=unspecified
      username: postgres
      password: 123456
      initial-size: 1
      min-idle: 3
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20


  redis:
    host: 127.0.0.1
    database: 15
    port: 6379
    password: 123456
    timeout: 100ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 1
        max-idle: 8
      shutdown-timeout: 100ms

mybatis-plus:
  mapper-locations: classpath*:com/lokiy/learning/**/mapper/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true


security:
  jwt:
    expiration-time: 86400
    refresh-time: 604800
    issuer: lokiy
    signing-key: lokiy
  exclude-urls: /sys/auth/login